### PR TITLE
Update rdf-canonize.

### PR DESCRIPTION
**Pull request by davidlehn**

### CODE REVIEW

**Comment by davidlehn** [comment]
@dlongley `setImmediate` polyfill was removed in rdf-canonize and now karma tests fail.  Should that be restored there or should the webpack/karma setups be changed to use the builtin polyfill?

**Comment by dlongley** [comment]
The webpack/karma setups should be changed to use the builtin polyfill.

**Comment by davidlehn** [comment]
Ok.  Such polyfills are removed in webpack 5, so when that migration happens we'll have to use https://github.com/yuzujs/setImmediate directly.

**Comment by davidlehn** [comment]
Upon further consideration, going to go with the `setimmediate` package directly in `rdf-canonize` to hopefully simplify things so packages like this don't have to do anything and will be ready for webpack v5.

**Pull request merged**
